### ISSUE TITLE
Maintenance state

### ISSUE THREAD

**Issue by rhodgkins** [highlycaffeinated/mailgun-js#258]
@highlycaffeinated have you taken over this repo from @bojand?

**Comment by highlycaffeinated** [comment]
Hi Rich,

Yes, I temporarily have this repo. We (Mailgun) are taking it over and in the process of merging it into the repo by the same name in our org.

**Comment by rhodgkins** [comment]
Thanks for the reply - this is good news! It might be worth updating the README message to reflect this (even if its temporary) because people will think this is still unmaintained...!

**Comment by highlycaffeinated** [comment]
Great idea. I didn’t bother at first because I thought the transition would happen much more quickly.
